// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetStive.Helpers;

#nullable disable

namespace ProjetStive.Migrations
{
    [DbContext(typeof(ProjetStiveContext))]
    [Migration("20230105103612_ajout_stock")]
    partial class ajout_stock
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetStive.client", b =>
                {
                    b.Property<int>("ID_Client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DDN")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("adresse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pays")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID_Client");

                    b.ToTable("client");
                });

            modelBuilder.Entity("ProjetStive.quantite", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnneeBtl")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ID_Client")
                        .HasColumnType("int");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nbcommande")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("quantite");
                });

            modelBuilder.Entity("ProjetStive.societe_negosud", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Annee_de_la_Bouteille")
                        .HasColumnType("int");

                    b.Property<int>("Date_de_Commande")
                        .HasColumnType("int");

                    b.Property<string>("Marque_de_Vin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nbre_de_Vin_Commande")
                        .HasColumnType("int");

                    b.Property<string>("Type_de_Vin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("societe_Negosuds");
                });

            modelBuilder.Entity("ProjetStive.stock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nombre")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
